/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package voting_blockchain;

import java.awt.Image;
import java.util.ArrayList; 
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import javax.swing.table.TableModel;


/**
 *
 * @author ELCOT
 */
public final class add_partys_view extends javax.swing.JFrame {
public static String ur1="jdbc:mysql://localhost:3306/voting_blockchain";

 
    

    /**
     * Creates new form add_partys_view
     */
    public add_partys_view() {
        initComponents();
          populateJtable();
         
    }
    First_party jsi = new First_party();
    Second_party jsi1= new Second_party();
    public void populateJtable(){
        MyQuery mq = new MyQuery();
        ArrayList<product2> list = mq.BindTable();
        String[] columnName = { "PARTY_NAME","PARTY_IMAGE","CONDITATE_NAME"};
        Object[][] rows = new Object[list.size()][3];
        for(int i=0;i<list.size();i++)
        {
            rows[i][0]= list.get(i).getpartyname();
            rows[i][2]= list.get(i).getconditate();
            
           if(list.get(i).getparty_image()!= null) 
           {
            
            ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getparty_image()).getImage().getScaledInstance(250,120, Image.SCALE_SMOOTH));
            rows[i][1]= image;
            }
            else
            {
                rows[i][1]=null;
            }
          
        }
        TheModel model = new TheModel (rows,columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("          search");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 20));
        jPanel2.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 710, 23));

        jLabel3.setText("          search");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 950, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 51,200));
        jTable1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 0, 0));
        jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 950, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting_blockchain/voted_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        setSize(new java.awt.Dimension(1370, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     //  String name1=a1.getText().toString().trim();  
       
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 int row = jTable1.rowAtPoint(evt.getPoint());
 int col=jTable1.columnAtPoint(evt.getPoint());
 int index =jTable1.getSelectedRow();
  TableModel model = jTable1.getModel();
 if(row==0 &&  col>=0)
 {
      
       String partyname = model.getValueAt(index,0).toString();
       ImageIcon image1= (ImageIcon)jTable1.getValueAt(index,1);
      // String conditate_name = model.getValueAt(index,2).toString();
      Image image2=image1.getImage().getScaledInstance(250,250,Image.SCALE_SMOOTH);
      ImageIcon image3 = new ImageIcon(image2);
       jsi.setVisible(true);
       jsi.pack();
       jsi.setLocationRelativeTo(null);
       jsi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
       jsi.a2.setText(partyname);
       jsi.a3.setIcon(image3);
       
 }
 else if(row==1 && col>=1)
 {
     String partyname = model.getValueAt(index,0).toString();
      ImageIcon image1= (ImageIcon)jTable1.getValueAt(index,1);
      // String conditate_name = model.getValueAt(index,2).toString();
      Image image2=image1.getImage().getScaledInstance(250,250,Image.SCALE_SMOOTH);
      ImageIcon image3 = new ImageIcon(image2);
       jsi1.setVisible(true);
       jsi1.pack();
       jsi1.setLocationRelativeTo(null);
       jsi1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       jsi1.a2.setText(partyname);
        jsi1.a3.setIcon(image3);
 }
       
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_partys_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new add_partys_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
