/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package voting_blockchain;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ELCOT
 */
public class Add_voters extends javax.swing.JFrame {
    String s;

    /**
     * Creates new form Add_voters
     */
    public Add_voters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vd = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        pc = new javax.swing.JTextField();
        reg = new javax.swing.JTextField();
        fp = new javax.swing.JTextField();
        profile = new javax.swing.JButton();
        db = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153,200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Sitka Heading", 1, 13)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 240, 35));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 1020, 70));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153,220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel2.setText("DOB");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 130, 25));

        pp.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        pp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel2.add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 190, 160));

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel4.setText("VOTER ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, 25));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel5.setText("NAME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 25));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel6.setText("MOBILE NUMBER");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, 25));

        vd.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(vd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 25));

        nm.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 25));

        mn.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 170, 25));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel7.setText("ADHAR NUMBER");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 25));

        jLabel8.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel8.setText("PINCODE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 130, 25));

        jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel9.setText("REGION");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 130, 25));

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel10.setText("FINGERPRINT");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 130, 25));

        ad.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 25));

        pc.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 170, 25));

        reg.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 170, 25));

        fp.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jPanel2.add(fp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 170, 25));

        profile.setBackground(new java.awt.Color(0, 51, 204));
        profile.setFont(new java.awt.Font("Sitka Heading", 1, 12)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("BROWSE");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel2.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 120, 30));

        db.setBackground(new java.awt.Color(255, 255, 255));
        db.setFont(new java.awt.Font("Sitka Subheading", 0, 15)); // NOI18N
        jPanel2.add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 170, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 1020, 330));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153,150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting_blockchain/topborder.png"))); // NOI18N
        jLabel3.setText("Blockchain voting");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting_blockchain/perfect_party.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        setSize(new java.awt.Dimension(1370, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String Aadhar_number = ad.getText().toString().trim();
     String voter_ID = vd.getText().toString().trim();
      String Name = nm.getText().toString().trim();
       String Mobile_number = mn.getText().toString().trim();
        String DOB = db.getDateFormatString().toString().trim();
         String Pincode = pc.getText().toString().trim();
          String Region = reg.getText().toString().trim();
           String Fingerprint = fp.getText().toString().trim();
            String Profile = pp.getText().toString().trim();
            int cnt=Mobile_number.length();
            int adhar=Aadhar_number.length();
            
              if((adhar!=12))                 
                  {
                      JOptionPane.showMessageDialog(null,"Enter the 12 digit adhar number !");
                  }
               else if((cnt!=10))
                  {
                      JOptionPane.showMessageDialog(null,"Please Enter your mobile number");
                  }
              else if((Aadhar_number.isEmpty())||(voter_ID.isEmpty())||(Name.isEmpty())||(Pincode.isEmpty())||(DOB.isEmpty())||(Region.equals(""))||(Fingerprint.equals("")))
                 {
                     JOptionPane.showMessageDialog(null,"Please Enter the all Field");
                     // c.setText("Enter the all field");
                 }
             else
                  {
    try
        {
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost/voting_blockchain","root","");
                  PreparedStatement ps = con.prepareStatement("insert into add_voters(Aadhar_number,voter_ID,Name,Mobile_number,DOB,Pincode,Region,Fingerprint,Profile) values(?,?,?,?,?,?,?,?,?)");
                  InputStream is = new FileInputStream(new File(s));
                  ps.setString(1,ad.getText());
                  ps.setString(2,vd.getText());
                  ps.setString(3,nm.getText());
                  ps.setString(4,mn.getText());
                  ps.setString(5,db.getDateFormatString());
                  ps.setString(6,pc.getText());
                  ps.setString(7,reg.getText());
                  ps.setString(8,fp.getText());
                  ps.setBlob(9,is);
                     
                      ps.executeUpdate();
                     JOptionPane.showMessageDialog(null,"Success");
                  
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser =new JFileChooser();
       fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
      FileNameExtensionFilter filter =new FileNameExtensionFilter("Image Files","jpg","png","gif","jpeg");
      fileChooser.addChoosableFileFilter(filter);
      
      
      int result =fileChooser.showSaveDialog(null);
       
      if(result == JFileChooser.APPROVE_OPTION) {
              
              File selectedFile = fileChooser.getSelectedFile();
              String fname=selectedFile.getAbsolutePath();
              System.out.print(fname);
              pp.setIcon(ResizeImage(fname));
             s = fname;
      }
      else if(result == JFileChooser.CANCEL_OPTION){
          System.out.println("no data");
      } 
  
    }//GEN-LAST:event_profileActionPerformed
 public ImageIcon ResizeImage (String imgPath){
    ImageIcon MyImage = new ImageIcon(imgPath);
    Image img = MyImage.getImage();
    Image newImage = img.getScaledInstance(pp.getWidth(),pp.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImage);
        return image;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new Add_voters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private com.toedter.calendar.JDateChooser db;
    private javax.swing.JTextField fp;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField pc;
    private javax.swing.JLabel pp;
    private javax.swing.JButton profile;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField vd;
    // End of variables declaration//GEN-END:variables
}
