/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package voting_blockchain;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ELCOT
 */
public class Second_party extends javax.swing.JFrame {

    /**
     * Creates new form ADMK
     */
    public Second_party() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        a2 = new javax.swing.JLabel();
        ss = new javax.swing.JPanel();
        a3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("N0,VOTE");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 180, 33));

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("YES,VOTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 190, 33));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTER YOUR PRIVATE KEY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(0, 0, 51))); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 410, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 35));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 250, 35));

        ss.setBackground(new java.awt.Color(0, 0, 0,80));

        javax.swing.GroupLayout ssLayout = new javax.swing.GroupLayout(ss);
        ss.setLayout(ssLayout);
        ssLayout.setHorizontalGroup(
            ssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        ssLayout.setVerticalGroup(
            ssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        getContentPane().add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 250, 180));

        jPanel2.setBackground(new java.awt.Color(0,0,0,120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("  Confirm key !");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting_blockchain/confirmkey.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        setSize(new java.awt.Dimension(730, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String PARTY_IMAGE =a3.getText().toString().trim();
        String CONDITATE_NAME = a2.getText().toString().trim();
       

        if((PARTY_IMAGE.isEmpty())&&(CONDITATE_NAME.isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"Your source missing !");
        }

        else
        {
            try
            {
                
                MessageDigest md = MessageDigest.getInstance("SHA-256");
                md.update(PARTY_IMAGE.getBytes());
                md.update(CONDITATE_NAME.getBytes());
                byte[] hashBytes = md.digest();
                StringBuilder VOTED_HASH= new StringBuilder();
                for(byte hashByte : hashBytes)
                {
                    VOTED_HASH.append(Integer.toString((hashByte & 0xff) + 0*100,16).substring(1));
                }
                String acno="root";
                String password="";
                String sql="SELECT * FROM  user_ballotex ";
                String ur1="jdbc:mysql://localhost:3306/voting_blockchain";
                Connection connection=DriverManager.getConnection(ur1,acno,password);       
                Statement stmt=(Statement)connection.createStatement();
                ResultSet rs=stmt.executeQuery(sql);
                String USER_DATA="";
        
      
        while(rs.next())
        {
             USER_DATA=(rs.getString(2));
            
        }
               
                
             

                String url="jdbc:mysql://localhost:3306/voting_blockchain";
                Connection con=DriverManager.getConnection(url,"root","");
                Statement stmt2=(Statement)con.createStatement();
                Statement stmt3=(Statement)con.createStatement();
                String qry="Select max(id) as Maxid from Second_party";
                
                ResultSet rs1=stmt3.executeQuery(qry);
                int id1=0;
                if(rs1.next())
                {
                    id1=rs1.getInt("Maxid");
                }
                int id2=id1+1;

                String ins ="insert into Second_party values('"+id2+"','"+USER_DATA+"','"+VOTED_HASH+"','voted')";

                int n=stmt2.executeUpdate(ins);
                if(n==1)
                {
                    JOptionPane.showMessageDialog(null,"Success");
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Failed");
                }

            } catch ( SQLException | NoSuchAlgorithmException ex) {
                Logger.getLogger(Second_party.class.getName()).log(Level.SEVERE, null, ex);
            }
            // TODO add your handling code here:

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second_party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_party().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel a2;
    public javax.swing.JLabel a3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel ss;
    // End of variables declaration//GEN-END:variables
}
