/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package voting_blockchain;

import java.awt.Image;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ELCOT
 */
public class User_details extends javax.swing.JFrame {
public static String USER_DATA;
    /**
     * Creates new form User_details
     */
    public User_details() {
     
        initComponents();
       
     showItem(pos);
    }
    int pos = 0;
    public Connection getConnection()
    {
        Connection con = null;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/voting_blockchain","root","");
        }catch(SQLException ex){
        }
        return con;
    }

    public List<Item> getItemsList()
    {
       try{
           Connection connection = getConnection();
           Statement st = connection.createStatement();
         //  String sql="SELECT * FROM Sales where User='"+UserLogin.num+"'";
           ResultSet rs = st.executeQuery("SELECT * FROM add_voters");
           List<Item> list = new ArrayList<Item>();
           Item item;
           while(rs.next())
           {
               item = new Item(rs.getString("voter_ID"),rs.getString("Name"),rs.getString("Mobile_number"),
                       rs.getString("DOB"),rs.getString("Region"),rs.getBytes("Profile"));
               
               list.add(item);
           }
           return list;
       } catch(SQLException e){
           return null;
       }
    }
    
    public void showItem(int index)
    {
        vd.setText(getItemsList().get(index).getvoterid());
         nm.setText(getItemsList().get(index).getname());
          mn.setText(getItemsList().get(index).getmobile_number());
           db.setText(getItemsList().get(index).dob());
            reg.setText(getItemsList().get(index).region());
            
            ImageIcon icon = new ImageIcon(getItemsList().get(index).getprofile());
            Image image = icon.getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH);
            
            pp.setIcon(new ImageIcon(image));
            
           
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        reg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vd = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        mn = new javax.swing.JLabel();
        db = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        c = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Sitka Heading", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 150, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 960, 70));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        reg.setForeground(new java.awt.Color(255, 255, 255));
        reg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 270, 25));

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGION");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, 25));

        pp.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        pp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel3.add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 200, 180));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTACT");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 25));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOB");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 25));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VOTER ID");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 25));

        vd.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        vd.setForeground(new java.awt.Color(255, 255, 255));
        vd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(vd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 270, 25));

        nm.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        nm.setForeground(new java.awt.Color(255, 255, 255));
        nm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 270, 25));

        mn.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        mn.setForeground(new java.awt.Color(255, 255, 255));
        mn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 270, 25));

        db.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        db.setForeground(new java.awt.Color(255, 255, 255));
        db.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 270, 25));

        jLabel12.setFont(new java.awt.Font("Sitka Heading", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NAME");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 130, 25));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 960, 320));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 400, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting_blockchain/voted_2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        setSize(new java.awt.Dimension(1370, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
     String voter_ID = vd.getText().toString().trim();
      String Name = nm.getText().toString().trim();
       String Mobile_number = mn.getText().toString().trim();
        String DOB = db.getText().toString().trim();
          String Region = reg.getText().toString().trim();
       
           
            
              if((voter_ID.isEmpty())||(Name.isEmpty())||(DOB.isEmpty())||(Mobile_number.isEmpty())||(Region.isEmpty()))                 
                  {
                      JOptionPane.showMessageDialog(null,"Your source missing !");
                  }
              else if((voter_ID.isEmpty())||(Name.isEmpty())||(DOB.isEmpty())||(Mobile_number.isEmpty())||(Region.isEmpty()))
              {
                    c.setText("Please contact the helpline !");
              }
             else
                  {
    try
        {
              MessageDigest md = MessageDigest.getInstance("SHA-256");
                md.update(voter_ID.getBytes());
                 md.update(Name.getBytes());
                  md.update(DOB.getBytes());
                   md.update(Mobile_number.getBytes());
                    md.update(Region.getBytes());
                   
                //     md.update(Profile.getBytes());
                   //   md.update(Email.getBytes());
                    //   md.update(Emailotp.getBytes());
                byte[] hashBytes = md.digest();
                StringBuilder USER_DATA= new StringBuilder();
                for(byte hashByte : hashBytes)
                {
                   USER_DATA.append(Integer.toString((hashByte & 0xff) + 0*100,16).substring(1));
                }
             
                String url="jdbc:mysql://localhost:3306/voting_blockchain";
//                Class.forName("con.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(url,"root","");
                Statement stmt=(Statement)con.createStatement();
                Statement stmt1=(Statement)con.createStatement();
                String qry="Select max(id) as Maxid from user_ballotex";
                ResultSet rs=stmt1.executeQuery(qry);
                int id1=0;
                if(rs.next())
                {
                    id1=rs.getInt("Maxid");
                }
                int id2=id1+1;
      
          
             String ins ="insert into user_ballotex values('"+id2+"','"+USER_DATA+"')";
                   
                    int n=stmt.executeUpdate(ins);
                    if(n==1)
                    {
                        JOptionPane.showMessageDialog(null,"Success");
                          new add_partys_view().setVisible(true);
                         
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Failed");
                    }
                   
                  
                    } catch ( SQLException | NoSuchAlgorithmException ex) {
                      Logger.getLogger(User_details.class.getName()).log(Level.SEVERE, null, ex);
            }
                      
                  
       
    }    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new User_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c;
    private javax.swing.JLabel db;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel nm;
    private javax.swing.JLabel pp;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel vd;
    // End of variables declaration//GEN-END:variables
}
